version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: OcSenDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - './postgresDB:/var/lib/postgresql'
    networks:
      ocsen_network:
        ipv4_address: 172.80.0.2

  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5151:80
    depends_on:
      - db
    networks:
      ocsen_network:
        ipv4_address: 172.80.0.3

networks:
  ocsen_network:
    ipam:
      config:
        - subnet: 172.80.0.0/24